// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioBuilder.Data;

#nullable disable

namespace PortfolioBuilder.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20251020193928_Create_Second_Table_Skills")]
    partial class Create_Second_Table_Skills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortfolioBuilder.Data.Models.CareerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("careerEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("careerIcon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("careerJobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("careerLongDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("careerRoleTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("careerShortDescription")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("careerStateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CareerRecords");
                });

            modelBuilder.Entity("PortfolioBuilder.Data.Models.SkillsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("careerRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("skillDateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<string>("skillDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("skillProvider")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("skillTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("careerRecordId");

                    b.ToTable("SkillsRecords");
                });

            modelBuilder.Entity("PortfolioBuilder.Data.Models.SkillsRecord", b =>
                {
                    b.HasOne("PortfolioBuilder.Data.Models.CareerRecord", "careerRecord")
                        .WithMany("skills")
                        .HasForeignKey("careerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_SkillsRecord_CareerRecord");

                    b.Navigation("careerRecord");
                });

            modelBuilder.Entity("PortfolioBuilder.Data.Models.CareerRecord", b =>
                {
                    b.Navigation("skills");
                });
#pragma warning restore 612, 618
        }
    }
}
